server:
  port: ${SERVER_PORT:8082}

spring:
  application:
    name: conversion-service
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb+srv://dbuser:dbuser%40123@cluster.fwne9bx.mongodb.net/webtodesk_conversions?appName=cluster}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}