server:
  port: 8081

jwt:
  # Provided at runtime (GitHub Actions/Fly secrets)
  access-secret: ${JWT_ACCESS_SECRET}
  refresh-secret: ${JWT_REFRESH_SECRET}
  access-token-expiry: 900000
  refresh-token-expiry: 2592000000
  prefix: "Bearer "

spring:
  application:
    name: user-service
  profiles:
    active: dev

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
